In [ ]:

from PTLF.lab import lab_setup
lab_setup(settings_path='./ProjDir/MilitaryAircraftClassification/MilitaryAircraftClassification.json')
del lab_setup

In [2]:
from PTLF.experiment import *

In [3]:
get_ppls()

['trl01', 'trl02', 'trl03', 'trl04']

In [4]:
get_ppl_details()

,pplid,model,dataset,accuracy,auroc,f1score,auprc,loss,optimizer
0,trl01,my_models.Vgg19,my_datasets.DS1,my_metrics.Acc,my_metrics.AUPRC,my_metrics.F1Score,my_metrics.AUROC,my_losses.CrossEn,my_optimizers.OptAdam
1,trl02,my_models.ResN50,my_datasets.DS1,my_metrics.Acc,my_metrics.AUPRC,my_metrics.F1Score,my_metrics.AUROC,my_losses.CrossEn,my_optimizers.OptAdam
2,trl03,my_models.EffiB3,my_datasets.DS1,my_metrics.Acc,my_metrics.AUPRC,my_metrics.F1Score,my_metrics.AUROC,my_losses.CrossEn,my_optimizers.OptAdam
3,trl04,my_models.EffiB3,my_datasets.DS1,my_metrics.Acc,my_metrics.AUPRC,my_metrics.F1Score,my_metrics.AUROC,my_losses.CrossEn,my_optimizers.OptAdam

In [5]:
get_ppl_status()

,pplid,best_epoch,train_accuracy,train_auroc,train_f1score,train_auprc,train_loss,val_accuracy,val_auroc,val_f1score,val_auprc,val_loss,last_epoch
0,trl01,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10000.000000,0
1,trl02,5,0.867371,0.992595,0.864829,0.320353,0.278255,0.607814,0.899036,0.592966,0.318126,1.208467,5
2,trl03,9,0.474224,0.842454,0.462103,0.313451,1.448136,0.378133,0.743278,0.358861,0.302892,2.017782,9
3,trl04,5,0.279743,0.208188,0.262660,NaN,2.431915,0.397708,0.248018,0.380606,NaN,1.787129,5

In [34]:
P = PipeLine(pplid='trl03')
P.get_path(of='history')

'/mnt/work/stdML/PTLF/MAcC/ProjDir/MilitaryAircraftClassification/Histories/trl03.csv'

In [35]:
import pandas as pd

In [36]:
df  =  pd.read_csv(P.get_path(of='history'))
df

,epoch,train_accuracy,train_auroc,train_f1score,train_auprc,train_loss,train_duration,val_accuracy,val_auroc,val_f1score,val_auprc,val_loss,val_duration
0,1,0.221530,0.183934,0.204969,NaN,2.759044,627.722566,0.302136,0.218405,0.281303,NaN,2.257726,123.758185
1,2,0.224096,0.580477,0.206875,0.280519,2.755193,598.776888,0.306887,0.685295,0.289462,0.297685,2.241785,92.660021
2,3,0.337198,0.727105,0.323546,0.302273,2.077431,632.177429,0.339407,0.715970,0.321220,0.299400,2.095082,106.514840
3,4,0.385372,0.768056,0.372430,0.306025,1.854697,673.856779,0.360847,0.724965,0.342252,0.303113,2.035618,131.115113
4,5,0.409195,0.792444,0.396394,0.309325,1.723354,754.090185,0.356330,0.727783,0.340321,0.300900,2.035015,178.828876
5,6,0.428995,0.808440,0.417343,0.307658,1.637969,816.046091,0.363296,0.735024,0.346816,0.300766,2.135650,229.559464
6,7,0.451884,0.824711,0.438989,0.311879,1.548019,991.409730,0.372125,0.736325,0.355547,0.305079,2.026993,116.207220
7,8,0.464076,0.833835,0.451100,0.312330,1.493362,492.390127,0.369162,0.730211,0.351619,0.303941,2.044944,126.837911
8,9,0.474224,0.842454,0.462103,0.313451,1.448136,521.759291,0.378133,0.743278,0.358861,0.302892,2.017782,132.973533

In [37]:
P.cnfg

{'pplid': 'trl03',
 'args': {'dataset': {'loc': 'my_datasets.DS1', 'args': {}},
  'model': {'loc': 'my_models.EffiB3',
   'args': {'dropout': 0.2,
    'fine_tune_last': 1,
    'pre_trained_path': './preTraineds/efficientnet_b3_rwightman-cf984f9c.pth'}},
  'loss': {'loc': 'my_losses.CrossEn', 'args': {}},
  'optimizer': {'loc': 'my_optimizers.OptAdam',
   'args': {'learning_rate': 0.001}},
  'metrics': {'accuracy': {'loc': 'my_metrics.Acc', 'args': {}},
   'auroc': {'loc': 'my_metrics.AUPRC',
    'args': {'average': 'macro', 'multi_class': 'ovr'}},
   'f1score': {'loc': 'my_metrics.F1Score', 'args': {'average': 'macro'}},
   'auprc': {'loc': 'my_metrics.AUROC', 'args': {'average': 'macro'}}},
  'train_data_src': './AirCrafts_data/Training/',
  'val_data_src': './AirCrafts_data/Valid/',
  'train_batch_size': 32,
  'val_batch_size': 32},
 'used': '',
 'best': {'epoch': 0},
 'last': {'epoch': 0}}

In [6]:
qry = "model=my_models.EffiB3"

filter_ppls(query=qry, params=True)

,dropout,fine_tune_last,pre_trained_path
trl03,0.2,1,./preTraineds/efficientnet_b3_rwightman-cf984f...
trl04,0.2,10,./preTraineds/efficientnet_b3_rwightman-cf984f...

In [52]:
qry = "dataset=my_datasets.DS1"

filter_ppls(query=qry)

['trl02', 'trl03', 'trl04']

In [53]:
filter_ppls(query=f"{qry}>")

[]

In [54]:
filter_ppls(query=qry, params=True)

Empty DataFrame
Columns: []
Index: []